Repository Parasolumc/PARASOL-SERVER, pull requests merged in 2023-08, with the labels that each got.

#23 [FIX] 우산 최대 갯수 삭제
  src/main/java/umc/parasol/domain/umbrella/application/UmbrellaService.java
  src/main/java/umc/parasol/domain/umbrella/domain/Umbrella.java
Labels: feature ⛱

#24 [FIX] History 기록 조회 시 대여일이 현재보다 가까운 순으로 정렬되도록 수정
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
  src/main/java/umc/parasol/domain/history/domain/repository/HistoryRepository.java
  src/main/java/umc/parasol/domain/history/presentation/HistoryController.java
Labels: feature ⛱

#25 [FEAT] 우산 추가 자유롭게 할 수 있도록 변경
  src/main/java/umc/parasol/domain/umbrella/application/UmbrellaService.java
  src/main/java/umc/parasol/domain/umbrella/presentation/UmbrellaController.java
Labels: feature ⛱

#28 [FEAT] 이전 비밀번호와 새 비밀번호가 같은지 검사
  src/main/java/umc/parasol/domain/member/application/MemberService.java
Labels: feature ⛱

#29 [FEAT]: 우산 판매 API 개발
  build.gradle
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
  src/main/java/umc/parasol/domain/history/dto/HistoryRes.java
  src/main/java/umc/parasol/domain/sell/application/SellService.java
  src/main/java/umc/parasol/domain/sell/domain/Sell.java
  src/main/java/umc/parasol/domain/sell/domain/repository/SellRepository.java
  src/main/java/umc/parasol/domain/sell/dto/SellResultRes.java
  src/main/java/umc/parasol/domain/sell/presentation/SellController.java
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
  src/main/java/umc/parasol/domain/shop/dto/UpdateUmbrellaReq.java
  src/main/java/umc/parasol/domain/umbrella/application/UmbrellaService.java
  src/main/java/umc/parasol/domain/umbrella/domain/repository/UmbrellaRepository.java
  src/main/java/umc/parasol/domain/umbrella/presentation/UmbrellaController.java
Labels: feature ⛱

#31 [FEAT] 회원 탈퇴 기능 추가
  src/main/java/umc/parasol/domain/history/domain/repository/HistoryRepository.java
  src/main/java/umc/parasol/domain/member/application/MemberService.java
  src/main/java/umc/parasol/domain/member/presentation/MemberController.java
Labels: feature ⛱

#32 [FIX] read-only 문제 해결
  src/main/java/umc/parasol/domain/auth/application/AuthSignService.java
Labels: fix ☔️

#33 [FIX] HttpMessageNotReadableException 오류 해결
  src/main/java/umc/parasol/domain/auth/dto/RefreshTokenReq.java
Labels: fix ☔️

#34 [FIX] HttpMessageNotReadableException 오류 해결
  src/main/java/umc/parasol/domain/auth/dto/RefreshTokenReq.java
Labels: fix ☔️

#35 [FIX] 반납 지점 같을 시 종료 지점 설정 오류 해결
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
Labels: fix ☔️

#36 [FIX] 내역 조회 시 endShop이 전부 null로 저장되는 문제 해결
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
Labels: fix ☔️

#37 [FIX]: 일반 사용자만 판매 가능하도록 변경
  src/main/java/umc/parasol/domain/sell/application/SellService.java
Labels: fix ☔️

#42 [FEAT] : 알림 조회 API 개발
  src/main/java/umc/parasol/domain/notification/application/NotificationService.java
  src/main/java/umc/parasol/domain/notification/domain/Notification.java
  src/main/java/umc/parasol/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/umc/parasol/domain/notification/dto/NotificationRes.java
  src/main/java/umc/parasol/domain/notification/presentation/NotificationController.java
Labels: feature ⛱

#43 [FEAT] : 알림 삭제 API 개발
  src/main/java/umc/parasol/domain/notification/application/NotificationService.java
  src/main/java/umc/parasol/domain/notification/domain/Notification.java
  src/main/java/umc/parasol/domain/notification/presentation/NotificationController.java
Labels: feature ⛱

#44 [FEAT] 사진 추가/삭제 기능 재개발
  src/main/java/umc/parasol/domain/image/application/ImageService.java
  src/main/java/umc/parasol/domain/shop/presentation/ShopController.java
  src/main/java/umc/parasol/global/infrastructure/S3Uploader.java
Labels: feature ⛱

#45 [REFACTOR] : response null값 빈스트링으로 대체
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
Labels: refactoring 🌈

#46 [FIX] 엔티티 직접 반환 및 프록시 이슈 해결
  src/main/java/umc/parasol/domain/verify/application/VerifyService.java
  src/main/java/umc/parasol/domain/verify/dto/VerifyResponse.java
Labels: fix ☔️

#47 [FIX] 우산 대여 기록 관련 null 응답 empty & 다른 값으로 변경
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
Labels: fix ☔️

#48 [REFACTOR] 매장 조회 방식 변경
  src/main/java/umc/parasol/domain/shop/application/ShopSearchService.java
  src/main/java/umc/parasol/domain/shop/presentation/ShopController.java
Labels: refactoring 🌈

#50 [fix] 한글파일 사진 업로드 이슈 해결
  src/main/java/umc/parasol/domain/image/domain/Image.java
  src/main/java/umc/parasol/global/infrastructure/S3Uploader.java
Labels: fix ☔️

#51 [FIX] : 로그인 ResponseBody에 MemberID 추가
  src/main/java/umc/parasol/domain/auth/application/AuthSignService.java
  src/main/java/umc/parasol/domain/auth/dto/AuthRes.java
Labels: fix ☔️

#52 [FIX] : 대여 및 반납처리과정, URL 변경
  src/main/java/umc/parasol/domain/history/application/HistoryService.java
  src/main/java/umc/parasol/domain/history/presentation/HistoryController.java
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
  src/main/java/umc/parasol/domain/shop/presentation/ShopController.java
Labels: fix ☔️

#55 [feat] TimeTable 생성 및 변경
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
  src/main/java/umc/parasol/domain/shop/domain/Shop.java
  src/main/java/umc/parasol/domain/shop/dto/ShopListRes.java
  src/main/java/umc/parasol/domain/shop/dto/ShopRes.java
  src/main/java/umc/parasol/domain/shop/dto/UpdateInfoReq.java
  src/main/java/umc/parasol/domain/timetable/domain/Day.java
  src/main/java/umc/parasol/domain/timetable/domain/TimeTable.java
  src/main/java/umc/parasol/domain/timetable/domain/repository/TimeTableRepository.java
  src/main/java/umc/parasol/domain/timetable/dto/TimeTableReq.java
  src/main/java/umc/parasol/domain/timetable/dto/TimeTableRes.java
Labels: feature ⛱

#56 [FIX] TimeTable 엔티티 경로 수정 및 예약어 리팩터링
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
  src/main/java/umc/parasol/domain/timetable/domain/TimeTable.java
  src/main/java/umc/parasol/domain/timetable/domain/repository/TimeTableRepository.java
Labels: fix ☔️

#57 [fix] Notification 의존 삭제
  src/main/java/umc/parasol/domain/shop/application/ShopService.java
Labels: fix ☔️

#59 [FIX]: 알림 조회 response 변경
  src/main/java/umc/parasol/domain/notification/application/NotificationService.java
  src/main/java/umc/parasol/domain/notification/dto/NotificationRes.java
Labels: fix ☔️

#60 deploy 작업본을 develop에 merge
  .github/workflows/deploy.yml
  Dockerfile
  src/main/java/umc/parasol/ParasolApplication.java
  src/main/java/umc/parasol/domain/common/BaseEntity.java
  src/main/java/umc/parasol/domain/history/dto/HistoryRes.java
  src/main/java/umc/parasol/domain/notification/dto/NotificationRes.java
  src/main/java/umc/parasol/domain/sell/application/SellService.java
  src/main/java/umc/parasol/domain/sell/presentation/SellController.java
  src/main/java/umc/parasol/domain/timetable/domain/Day.java
  src/main/java/umc/parasol/domain/verify/dto/VerifyResponse.java
Labels: feature ⛱, deployment 🚀
